-
  name: "changing conf file"
  hosts: web1
  become: yes
  tasks:
    -
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'DirectoryIndex index.html'
        replace: 'DirectoryIndex index.php'
        backup: yes
