-
  name: variable check for hosts
  hosts: web1
  tasks:
    - debug:
        msg: System {{ inventory_hostname }} private ip is {{ ansible_all_ipv4_addresses }}
    -
      debug:
        var: hostvars[inventory_hostname]
