-
  name: Installing multiple packages
  hosts: target1
  become: yes
  vars:
    packages:
      - make
      - mutt
      - zip
  tasks:
    -
      name: "installing packages"
      yum:
        name: '{{ item }}'
        state: present
      with_items: '{{ packages }}'
