-
  name: var check
  hosts: web1
  vars:
    local_home: "{{lookup('env','HOME')}}"
  tasks:
    -
      name: display env vars
      command: 'echo "{{ local_home }}"'
      register: home_output
    -
      debug:
        var: home_output.stdout_lines
    -
      name: remote env vars
      command: 'echo "{{ ansible_env.HOME}}"'
      register: remote_home
    -
      debug:
        var: remote_home.stdout_lines
