-
  name: "Installing packages based on os"
  hosts: target1
  become: yes
  tasks:
    -
      name: "installing mysql in centos"
      yum:
        name: mysql
        state: present
      when: ansible_os_family == "CentOS" or ansible_os_family == "CentOS Linux"

    -
      name: "installing mutt in rhel"
      yum:
        name: mutt
        state: present
      when: ansible_os_family == "Redhat"
